# This file should have all the dependencies for development excluding the specific to the backends.
name: ibis-dev
channels:
  - conda-forge
dependencies:
  # Ibis hard dependencies
  - multipledispatch
  - numpy
  - pandas
  - pytz
  - regex
  - toolz

  # Ibis soft dependencies
  - sqlalchemy
  - python-graphviz

  # Dev tools
  - asv
  - black=19.10b0
  - click # few scripts in ci/
  - flake8
  - flake8-comprehensions # used by flake8, linting of unnecessary comprehensions
  - isort
  - jinja2 # feedstock
  - mypy
  - plumbum # few scripts in ci/ and dev/
  - pydocstyle
  - pytest
  - pytest-cov
  - pytest-mock

  # Release
  - twine
  - wheel
  - conda-smithy
  - conda-build # feedstock
  - ruamel.yaml # feedstock
  - pygit2 # dev/genrelease.py

  # Docs
  - pip
  - pip:
    - pysuerga
  - ipython
  - jupyter
  - matplotlib
  - nbconvert
  - nbsphinx
  - nomkl
  - semantic_version=2.6 # https://github.com/ibis-project/ibis/issues/2027
  - sphinx<4.0.0 # https://github.com/ibis-project/ibis/issues/2771
  - sphinx-releases
  - sphinx_rtd_theme
