site_name: Ibis Project
site_url: https://ibis-project.org
strict: false # check for strictness when building the docs in CI
edit_uri: ""
repo_url: https://github.com/ibis-project/ibis
extra_css:
  - stylesheets/extra.css
  - stylesheets/code_select.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  logo: static/icons/ibis/logo.svg
  favicon: static/icons/ibis/logo.svg
  palette:
    # light mode toggle
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # dark mode toggle
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: docs/overrides
plugins:
  - search
  - autorefs
  - git-revision-date-localized
  - exclude:
      glob:
        - backends/template.md
        - backends/badges.md
        - backends/*_support_matrix.csv
        - backends/app/*
        - CONTRIBUTING.md
  - gen-files:
      scripts:
        - gen_matrix.py
        - gen_redirects.py
  - macros
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.sqlalchemy.org/objects.inv
            - https://arrow.apache.org/docs/objects.inv
            - http://pandas.pydata.org/pandas-docs/stable/objects.inv
          options:
            docstring_style: numpy
            filters:
              - "!^_"
              - "!^__"
              - "!^backend_table_type"
              - "!^column$"
              - "!^compiler$"
              - "!^do_connect"
              - "!^fetch_from_cursor"
              - "!^get_schema"
              - "!^reconnect"
              - "!^(context|database|select_builder|select|table|table_expr|translator)_class"
              - "!^same_kind"
              - "!^infer_(dtype_default|list|map|set|struct)$"
              - "!^highest_precedence$"
              - "!^scalar$"
              - "!^column$"
              - "!^option_context$"
              - "!Selector$"
              - "!^projection$"
            show_category_heading: true
            show_root_full_path: false
            show_root_heading: true
            show_root_toc_entry: true
            show_source: false
  - mkdocs-jupyter:
      execute: true
      ignore:
        - "*.py"
      execute_ignore:
        - "**/rendered/*.ipynb"
      include_source: true
      allow_errors: false
  - literate-nav
  - social
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/static/icons
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      provider: github
      repo_url_shortener: true
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      permalink_title: "Anchor link to this section for reference"
extra:
  project_name: "ibis"
  # maybe version goes here?
  team:
    - name: "Maintainers"
      members:
        - cpcloud
        - kszucs
        - jreback
        - gforsyth
        - jcrist
        - saulpw
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IbisData
    - icon: fontawesome/brands/github
      link: https://github.com/ibis-project/ibis/discussions
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/ibis-dev/Lobby
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/ibis
  support_levels:
    supported:
      icon: :material-check-decagram:{ .verified }
      description: Tested in CI. If this doesn't work for you, please [file an issue](https://github.com/ibis-project/ibis/issues/new).
    unknown:
      icon: :fontawesome-solid-triangle-exclamation:{ .caution }
      description: Not tested in CI. Unknown if this setup works.
    unsupported:
      icon: :material-cancel:{ .cancel }
      description: Unlikely to ever be supported or no upstream support.

copyright: "Copyright &copy; Ibis Maintainers"
