name: ibis-dev
channels:
  - conda-forge
dependencies:
  # runtime dependencies
  - apache-flink =1.20.0
  - atpublic >=2.3
  - black >=22.1.0,<25
  - clickhouse-connect >=0.5.23
  - datafusion >=0.6
  - db-dtypes >=0.3.0,<2
  - deltalake
  - duckdb-engine <1,>=0.1.8
  - filelock >=3.7.0,<4
  - fsspec >=2022.1.0
  - gcsfs
  - geopandas >=0.6
  - google-cloud-bigquery >=3,<4
  - google-cloud-bigquery-storage >=2,<3
  - impyla >=0.17
  - numpy >=1.23.2,<2
  - oracledb >=1.3.1
  - packaging >=21.3
  - pandas >=1.5.3,<3
  - parsy >=2
  - pins >=0.8.2
  - pip
  - uv>=0.4.29
  - polars >=1,<2
  - psycopg2 >=2.8.4
  - pyarrow >=10.0.1
  - pyarrow-hotfix >=0.4
  - pydata-google-auth
  - pydruid >=0.6.5
  - mysqlclient >=2.2.4
  - pyodbc >=4.0.39
  - pyspark >=3
  - python >=3.10
  - python-dateutil >=2.8.2
  - python-duckdb >=0.8.1
  - python-graphviz >=0.16
  - pytz >=2022.7
  - regex >=2021.7.6
  - requests >=2
  - rich >=13.8.0
  - shapely >=2,<3
  - snowflake-connector-python >=3.0.2
  - sqlglot >=22.5,<23.1
  - toolz >=0.11
  - trino-python-client >=0.321
  - openjdk <21
  # geospatial
  - leafmap >=0.29.6,<0.31
  # streaming
  - kafka-python
  # test dependencies
  - filelock >=3.7.0,<4
  - hypothesis >=6.58.0,<7
  - pytest >=8.2.0,<9
  - pytest-benchmark >=3.4.1,<5
  - pytest-clarity >=1.0.1,<2
  - pytest-cov >=3.0.0,<5
  - pytest-httpserver >=1.0.5,<2
  - pytest-mock >=3.6.1,<4
  - pytest-randomly >=3.10.1,<4
  - pytest-repeat >=0.9.1,<0.10
  - pytest-snapshot >=0.9.0,<1
  - pytest-xdist >=2.3.0,<4
  - pytest-timeout >=2.3.1,<3
  - requests >=2,<3
  # docs
  - quarto >=1.4
  - altair >=5.0.1
  - distributed >=2022.9.1
  - ipykernel >=6.25.1
  - itables >=1.6.3
  - jupyter-cache
  - nbclient >=0.8.0
  - plotly >=5.16.1
  - plotnine >=0.12.2
  - py-cpuinfo >=9
  - quartodoc >=0.6.1
  - seaborn
  # dev utilities
  - codespell >=2.2.6
  - go-shfmt
  - ipython
  - pre-commit
  - prettier
  - pyinstrument
  - ruff >=0.1.8
  - taplo
  - tqdm >=4.66.1
  - just
  - pip
  - pip:
      - lonboard==0.4.0
