name: Automatic Rebase
on:
  push:
    branches-ignore:
      # Ignore branches automatically created by this action
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
      # Don't automatically rebase branches created by WhiteSource Renovate
      - renovate**
  pull_request_target:
    types:
      - labeled
jobs:
  auto-rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.SQUAWK_BOT_APP_ID }}
          private_key: ${{ secrets.SQUAWK_BOT_APP_PRIVATE_KEY }}

      - uses: Label305/AutoRebase@v0.1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
