name: Conda lock PR
on:
  pull_request_target:
    types:
      - opened
      - reopened
    paths:
      - 'conda-lock/*.lock'
      - pyproject.toml
      - poetry.lock

jobs:
  conda_lock_comment:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ibis-project/ibis' }}
    steps:
      - name: Generate a GitHub token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@v2

      - name: add condalock comment
        uses: peter-evans/create-or-update-comment@v1
        with:
           token: ${{ steps.generate_token.outputs.token }}
           issue-number: ${{ github.event.number }}
           body: "/condalock"
