# vim: filetype=yaml
name: Dispatch conda lock

on:
  issue_comment:
    types:
      - created

jobs:
  condalock_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.SQUAWK_BOT_APP_ID }}
          private_key: ${{ secrets.SQUAWK_BOT_APP_PRIVATE_KEY }}

      - uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          issue-type: pull-request
          commands: condalock
