name: TPC-H

on:
  push:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - "**/*.md"
    branches:
      - master
      - "*.x.x"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - "**/*.md"
    branches:
      - master
      - "*.x.x"
  merge_group:

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tpch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: clone tpc-queries
        uses: actions/checkout@v3
        with:
          repository: ibis-project/tpc-queries
          path: ./tpc-queries
          ref: master

      - name: install python
        uses: actions/setup-python@v4
        id: install_python
        with:
          python-version: "3.11"

      - name: install tpc-queries dependencies
        working-directory: tpc-queries
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -U 'duckdb>=0.4' 'duckdb-engine>=0.6' 'pandas<2.1'

      - name: install ibis
        run: python -m pip install ".[sqlite,duckdb]"

      - name: generate tpc-h data
        working-directory: tpc-queries
        run: python -c "import duckdb; duckdb.connect('tpch.ddb').execute('CALL dbgen(sf=0.1)')"

      - name: run tpc-h queries
        working-directory: tpc-queries
        run: ./runtpc -i ibis -i duckdb -d 'tpch.ddb' -b 'duckdb'
