name: Update Release Branches
on:
  schedule:
    # run every 24 hours at 1 AM
    - cron: "1 */24 * * *"
  workflow_dispatch:

jobs:
  generate_branches:
    name: Query Release Branches
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: output branches list
        id: set-matrix
        run: |
          set -euo pipefail

          branches=$(git ls-remote --heads https://github.com/ibis-project/ibis.git \
              | sed -e 's#\t# #g' -e 's#refs/heads/##g' \
              | cut -d ' ' -f2 \
              | grep -P '\d+\.x\.x' \
              | xargs printf '"%s"' \
              | jq -rcMs '{branch: .}')

          echo "::set-output name=matrix::$branches"

  rebase_branch:
    name: Rebase ${{ matrix.branch }}
    runs-on: ubuntu-latest
    needs:
      - generate_branches
    strategy:
      matrix: ${{ fromJSON(needs.generate_branches.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - uses: tibdex/github-app-token@v1
        id: generate_pr_token
        with:
          app_id: ${{ secrets.SQUAWK_BOT_APP_ID }}
          private_key: ${{ secrets.SQUAWK_BOT_APP_PRIVATE_KEY }}

      - uses: tibdex/github-app-token@v1
        id: generate_pr_approval_token
        with:
          app_id: ${{ secrets.PR_APPROVAL_BOT_APP_ID }}
          private_key: ${{ secrets.PR_APPROVAL_BOT_APP_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@v4
        id: create_pr
        with:
          token: ${{ steps.generate_pr_token.outputs.token }}
          commit-message: "chore(${{ matrix.branch }}): rebase onto upstream"
          branch: "create-pull-request/rebase-${{ matrix.branch }}"
          base: ${{ matrix.branch }}
          delete-branch: true
          author: "ibis-squawk-bot[bot] <ibis-squawk-bot[bot]@users.noreply.github.com>"
          title: "chore(${{ matrix.branch }}): rebase onto upstream"
          body: ""
          labels: dependencies

      - uses: juliangruber/approve-pull-request-action@v1.1.1
        if: ${{ fromJSON(steps.create_pr.outputs.pull-request-number) != null }}
        with:
          github-token: ${{ steps.generate_pr_approval_token.outputs.token }}
          number: ${{ steps.create_pr.outputs.pull-request-number }}

      - uses: peter-evans/enable-pull-request-automerge@v2
        if: ${{ fromJSON(steps.create_pr.outputs.pull-request-number) != null }}
        with:
          token: ${{ steps.generate_pr_token.outputs.token }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: rebase
