name: PyPI Pre-Release

on:
  schedule:
    # weekly on Sunday
    - cron: "0 0 * * 0"

  # as needed by clicking through the github actions UI
  workflow_dispatch:

# we do not want more than one pre-release workflow executing at the same time, ever
concurrency:
  group: pre-release
  # cancelling in the middle of a release would create incomplete releases
  # so cancel-in-progress is false
  cancel-in-progress: false

jobs:
  pre-release:
    if: github.repository_owner == 'ibis-project'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install uv
        uses: astral-sh/setup-uv@v5.4.1

      - uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: compute ibis version
        id: get-version
        run: echo "value=$(just bump-version)" | tee -a "$GITHUB_OUTPUT"

      - name: build wheel and source dist
        run: uv build
        if: contains(steps.get-version.outputs.value, '.dev')

      - name: publish pre-release wheel to test pypi index
        if: contains(steps.get-version.outputs.value, '.dev')
        uses: pypa/gh-action-pypi-publish@db8f07d3871a0a180efa06b95d467625c19d5d5f
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: publish pre-release wheel to pypi
        if: contains(steps.get-version.outputs.value, '.dev')
        uses: pypa/gh-action-pypi-publish@db8f07d3871a0a180efa06b95d467625c19d5d5f
