name: Rebase
on:
  issue_comment:
    types: created

jobs:
  one:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/rebase'
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Set up git
      run: |
        git remote add upstream ${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}.git
        git config user.name rebase-bot
        git config user.email rebase-bot@github.com

    - name: Merge master
      run: git merge upstream/master

    - name: Push
      run: git push      
