name: Update setup.py

on:
  pull_request:
    paths:
      - ./dev/poetry2setup
      - ./dev/poetry2setup.py
      - pyproject.toml
      - poetry.lock

jobs:
  generate_setup_py:
    # this can only run on pull requests made from branches in the main ibis
    # repository ano not forks, since the add-and-commit action requires the
    # ability to push commits to the PR branch
    #
    # this condition checks whether the PR is coming from a branch in the main
    # repo
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: install nix
        uses: cachix/install-nix-action@v12

      - name: setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: ibis
          extraPullNames: nix-community,poetry2nix

      - name: generate setup.py
        run: ./dev/poetry2setup -o setup.py

      - name: setup git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          global: true
          name: ibis-project-bot[bot]
          email: ibis-project-bot[bot]@users.noreply.github.com

      - name: commit setup.py and push to pull request
        uses: EndBug/add-and-commit@v7
        with:
          add: setup.py
          author_name: ibis-project-bot[bot]
          author_email: ibis-project-bot[bot]@users.noreply.github.com
          message: "chore(setup.py): update"
          push: true
